Adding principal regarding querying/returning predicate inverses.
NCATSTranslator/TranslatorArchitecture pull request #38
Opened 2021-04-28 15:10 UTC by sierra-moxon

- PR reopened to contend with the readme vs. README issue.
- refactored 'should' to 'must'.
- added qualification that this principal applies to KGX files and TrAPI messages as well.

2021-05-03 15:19 UTC, codewarrior2000 commented
Perhaps it might be better to change in the README the wording from "This principal also applies ..." to "This principle also applies ..."

2021-05-03 16:36 UTC, patrickkwang requested changes

2021-05-03 16:36 UTC, patrickkwang commented on README.md
> +1. When querying and returning results with predicates, KPs and ARAs must be queried using the 'canonical' predicate (as opposed to its inverse), and must return the 'canonical' predicate.  There wil
```suggestion
1. When querying and returning results with predicates, KPs and ARAs must be queried using the 'canonical' predicate (as opposed to its inverse), and must return the 'canonical' predicate.  There will be two ways to identify the 'canonical' predicate in the biolink-model: canonical translator predicates will not be tagged with the 'inverse:' attribute, and canonical predicates will be tagged with an "annotations" flag with the tag: "biolink:canonical_predicate" and value: "True".  This principle also applies to KGX files and TRAPI messages.
```
The R stands for "reasoner".
🤷

2021-05-04 18:48 UTC, vdancik approved these changes

2021-05-04 18:48 UTC, bill-baumgartner approved these changes

2021-05-04 22:09 UTC, edeutsch approved these changes

2021-05-05 22:00 UTC, karthiksoman approved these changes

2021-05-05 22:07 UTC, suihuang-ISB approved these changes

2021-05-05 22:44 UTC, newgene approved these changes

2021-05-05 22:58 UTC, rtroper approved these changes

2021-05-06 04:14 UTC, karthiksoman approved these changes

2021-05-17 14:38 UTC, bill-baumgartner approved these changes

2021-05-17 16:18 UTC, vdancik approved these changes

2021-05-17 16:55 UTC, rtroper approved these changes

2021-05-17 17:18 UTC, patrickkwang approved these changes

2021-05-18 00:11 UTC, CaseyTa commented
@sierra-moxon, could you please clarify where it says 

> "canonical translator predicates will not be tagged with the 'inverse:' attribute"

Does this mean that only the non-canonical predicate will specify which predicate is its inverse? 

So take `biolink:superclass_of` and `biolink:subclass_of`. Currently, both have their inverses defined as each other. If `biolink:subclass_of` is defined as the canonical direction, then would it no longer specify `inverse: superclass of`, while `biolink:superclass_of` would keep its definition of `inverse: subclass of`? If this is the case, it might be slightly more inconvenient to find the inverse of a canonical predicate. It also seems unnecessary to remove the inverse if the canonical predicate will also be specified by `biolink:canonical_predicate`. 

This is just a very minor quibble, and either way, I'll approve of the changes.

2021-05-18 00:11 UTC, CaseyTa approved these changes

2021-05-18 15:24 UTC, sierra-moxon commented
> @sierra-moxon, could you please clarify where it says
> 
> > "canonical translator predicates will not be tagged with the 'inverse:' attribute"
> 
> Does this mean that only the non-canonical predicate will specify which predicate is its inverse?
> 
> So take `biolink:superclass_of` and `biolink:subclass_of`. Currently, both have their inverses defined as each other. If `biolink:subclass_of` is defined as the canonical direction, then would it no longer specify `inverse: superclass of`, while `biolink:superclass_of` would keep its definition of `inverse: subclass of`? If this is the case, it might be slightly more inconvenient to find the inverse of a canonical predicate. It also seems unnecessary to remove the inverse if the canonical predicate will also be specified by `biolink:canonical_predicate`.
> 
> This is just a very minor quibble, and either way, I'll approve of the changes.

Hi Casey!  Yep, your example is inline with the intention of this principle.  @cmungall's original idea for declaring the inverse was to only curate the predicate in one direction (ie: only the non-canonical predicate would have the 'inverse' attribute populated).  We added the biolink:canonical_predicate to make this a bit simpler to pull out from the canonical predicate itself.  We did open a ticket in the BMT repo, to make a helper function for this as well: https://github.com/biolink/biolink-model-toolkit/issues/30.

2021-05-18 16:27 UTC, cbizon approved these changes

2021-05-18 17:26 UTC, merged