central node properties
NCATSTranslator/TranslatorArchitecture pull request #87
Opened 2023-03-13 13:09 UTC by cbizon

This PR introduces the idea of a centralized node property server to be called by the ARS.

2023-03-20 19:01 UTC, andrewsu approved these changes

2023-03-20 20:15 UTC, newgene approved these changes

2023-03-21 18:32 UTC, CaseyTa approved these changes

2023-03-21 18:32 UTC, vdancik approved these changes

2023-03-22 00:40 UTC, np0625 requested changes

2023-03-22 20:43 UTC, suihuang-ISB approved these changes

2023-03-23 13:36 UTC, cbizon commented on README.md
Discussed on a call, but for posterity - "node" here means effectively TRAPI knowledge_graph node.

Node properties are not consistent across KPs/ARAs and the purpose of this is to provide consistency at the client/UI level.

In terms of process/interface we have some thoughts but that's somewhat outside the scope of this PR which is mostly to establish agreement on the idea of centralizing this function.

2023-04-05 18:46 UTC, cbizon commented
Open without no votes for several weeks - merging.

2023-04-05 18:46 UTC, merged